version: "3"

services:
  minio:
    image: minio/minio
    hostname: minio
    restart: always
    volumes:
      - ./seeiner/data/minio:/data/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
  hazelcast:
    image: hazelcast/hazelcast:latest
    hostname: hazelcast
    restart: always
    ports:
      - "5701:5701"
    environment:
      HZ_NETWORK_PUBLICADDRESS: 0.0.0.0:5701

